# Generated by Django 3.2 on 2021-05-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='file')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
